swagger: '2.0'
info:
  version: 3.0.0
  title: Provisioning users
  description: |
    Signup endpoints for TrustFile.  Provision users via API to be called using connectors.
    #### Testing:
    Test this endpoint @ https://stable.trustfile.avalara.com
    #### Security:
    Authentication/Auth header is required for either endpoint
    #### CORS:
    Access-Control-Allow-Headers: X-Requested-With
  contact:
    name: Trustfile API Support
    url: https://app.trustfile.com
    email: api@trustfile.com
host: app.trustfile.avalara.com
basePath: /v4
schemes:
  - http
  - https
consumes:
  - application/json
produces:
  - application/json
securityDefinitions:
  Authorization:
    type: apiKey
    in: header
    name: Authorization
    description: Key should be 'Bearer ' followed by the connectorToTFToken
paths:
  /company:
    get:
      tags:
        - Api
      operationId: GetCompany
      summary: 'Get Company via API GET '
      description: |
        * Data is expected as query string.
        * A message with the status will be sent back based on the data provided.
      parameters:
        - name: email
          in: query
          description: The Email address that needs to be searched.
          required: true
          type: string
      security:
        - Authorization: []
      responses:
        '200':
          description: Get Company successful response
          schema:
            type: object
            example:
              success: 'true'
              message: User already exists
            properties:
              success:
                type: boolean
              message:
                type: string
        '400':
          description: Get Company failure response
          schema:
            type: object
            example:
              success: 'false'
              error: No email address provided
            properties:
              success:
                type: boolean
              error:
                type: string
  /v4/company/signup:
    post:
      tags:
        - Api
      operationId: PostCompanySignup
      summary: Company signup via API POST
      description: |
        * All data is expected in the request body in a flat JSON format.
        * User Fields: email firstName lastName
        * Company fields: companyName companyPhone companyLine1 companyLine2 companyCity companyZip companyState companyCountry
        * companyName cannot be more than 50 chars
        * companyName must be unique
        * offerName
        * paymentId
        * The new user will receive an email to set their password
        * company token will be passed upon successful provisioning of the company
        * Once logged in, the user will be directed to set startDate for the connector
      parameters:
        - in: body
          name: body
          description: Company signup object
          required: true
          schema:
            $ref: '#/definitions/SignupBody'
            type: object
            required:
              - email
              - companyName
            example:
              email: test.me@gmail.com
              firstName: firstname
              lastName: lastname
              companyPhone: '4258776015'
              companyName: Best Company Ever
              companyLine1: '255 S King St.'
              companyLine2: 'P.O. Box 2321'
              companyCity: 'Seattle'
              companyZip: '98101'
              companyState: 'WA'
              campaignId: '2'
              paymentId: '123456789'
              offerName: 'TFShopifyApp'
            properties:
              email:
                type: string
                example: test.me@gmail.com
              firstName:
                type: string
              lastName:
                type: string
              companyName:
                type: string
              companyPhone:
                type: string
              companyLine1:
                type: string
              companyLine2:
                type: string
              companyLine3:
                type: string
              companyState:
                type: string
              companyCity:
                type: string
              companyZip:
                type: string
              companyCountry:
                type: string
              campaignId:
                type: string
              lsmr:
                type: string
              integratorId:
                type: string
              salesUserId:
                type: string
              salesUserEmail:
                type: string
              transactionType:
                type: string
              license:
                type: object
                properties:
                  paymentId:
                    type: string
                  totalPrice:
                    type: integer
      security:
        - Authorization: []
      responses:
        '200':
          description: Company creation successful response
          schema:
            type: object
            example:
              status: Success
              notification:
                message: Account Created.
                options:
                  level: success
              companyToken: d89c8c1d-6de2-4b3a-958b-74b674e3b823
            properties:
              status:
                type: string
              notification:
                type: object
                properties:
                  message:
                    type: string
                  options:
                    type: object
                    properties:
                      level:
                        type: string
              companyToken:
                type: string
        '400':
          description: Company creation failure response
          schema:
            type: object
            example:
              status: Failed
              notification:
                message: There was a problem creating your account. Account could not be created.
                options:
                  level: error
            properties:
              status:
                type: string
                description: Failed
              notification:
                type: object
                properties:
                  message:
                    type: string
                    description: Error message
                  options:
                    type: object
                    properties:
                      level:
                        type: string
definitions:
  SignupBody:
    type: object
    required:
      - email
      - firstName
      - lastName
      - companyPhone
      - companyName
      - companyLine1
      - companyCity
      - companyZip
      - companyState
      - campaignId
      - paymentId
      - offerName

    properties:
      email:
        type: string
        description: customer email
        example: 'test@avalara.com'
      firstName:
        type: string
        description: first name
        example: 'Fred'
      lastName:
        type: string
        description: last name
        example: 'Jackson'
      companyPhone:
        type: string
        description: company phone number
        example: '2068675309'
      companyName:
        type: string
        description: company name
        example: 'Avalara'
      companyLine1:
        type: string
        description: address line 1
        example: '255 S King St.'
      companyLine2:
        type: string
        description: address line 2 (optional)
        example: 'PO Box 2321'
      companyCity:
        type: string
        description: city
        example: 'Seattle'
      companyZip:
        type: string
        description: zip code
        example: '98102'
      companyState:
        type: string
        description: state
        example: 'WA'
      companyCountry:
        type: string
        description: country (optional)
        example: 'United States'
      campaignId:
        type: string
        description: TFO campaignId
        example: '70133000000y2dq'
      paymentId:
        type: string
        description: paymentId
        example: '1393033269'
      offerName:
        type: string
        description: TFO offer name
        example: 'TFShopifyApp'